// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAKKRTjbI8kBHxG1l_ii-3uYfgJb8gb_Q',
    appId: '1:134382658162:web:4334356c07909ffd80d8eb',
    messagingSenderId: '134382658162',
    projectId: 'my-notes-learning-flutter',
    authDomain: 'my-notes-learning-flutter.firebaseapp.com',
    storageBucket: 'my-notes-learning-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4AEaOk03n7HQrnYKCcc0Mmzk_Mx7nfQ8',
    appId: '1:134382658162:android:5bead175e0eaeca880d8eb',
    messagingSenderId: '134382658162',
    projectId: 'my-notes-learning-flutter',
    storageBucket: 'my-notes-learning-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnM8UNiu3FI4VO28BvdCCRSxUwUEi2pAE',
    appId: '1:134382658162:ios:2a1f1299a5fdfdc980d8eb',
    messagingSenderId: '134382658162',
    projectId: 'my-notes-learning-flutter',
    storageBucket: 'my-notes-learning-flutter.appspot.com',
    iosClientId: '134382658162-vqhgupno1ct1ceqvtohpjvu7oe84i5vk.apps.googleusercontent.com',
    iosBundleId: 'com.gentlekboy.mynotes',
  );
}
